# Site settings
title: Aidan Valente
email: valente.aidan@gmail.com
description: <b>Student at Washington and Lee University<br/><br/>Medieval & Renaissance Studies and Art History Major<br/><br/>Mellon Digital Humanities Undergraduate Fellow</b>
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Aidan Valente
street_address:
city:
state:
zip_code:
country:
phone:

icon: fa-adn # Font Awesome class for your site's icon

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/valenteaidan
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
